routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('Inicio');
})->name('Inicio');

Route::get('SobreMi', function () {
    return view('SobreMi');
});

Route::get('Portafolio', function () {
    return view('Portafolio');
});

Route::get('Contacto', function () {
    return view('Contacto');
});

Route::get('Login', function(){
	return view('Login');
});

Route::post('messages', function(){

	//Enviar un correo

	$data = request()->all();
	Mail::send("emails/message", $data, function($message) use ($data){

		$message->from($data['email'], $data['name'])
		->to('daninacho99@gmail.com', 'Daniel')
		->subject($data['subject']);

	});
	//Responder al usuario

	return back();

})->name('messages');
Auth::routes();
Route::get('/home', 'HomeController@index');



Route::resource('image','imageController');
Route::get('image/destroy/{id}',['as'=>'image/destroy','uses'=>'imageController@destroy']);
Route::get('image/search',['as'=>'image/search','uses'=>'imageController@search']);

app/Models/images.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class images extends Model
{
    protected $table = 'images';
    protected $fillable = ['images'];
    protected $guarded = ['id'];
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/ContentController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class ContentController extends Controller
{
    //Administrador
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/ImageController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\images as images;

class ImageController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $images = images::all();
        return \View::make('listimage',compact('images')); 
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return \View::make('images');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $images = new images;
        $images->id = $request->id;
        $images->images = $request->images;
        return redirect('image');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/Contacto.blade.php
@extends('layout')

@section('content')
	<!-- 
        ================================================== 
            Global Page Section Start
        ================================================== -->
        <section class="global-page-header">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <div class="block">
                            <h2>Contacto</h2>
                        </div>
                    </div>
                </div>
            </div>   
        </section><!--/#page-header-->


        <!-- 
        ================================================== 
            Contact Section Start
        ================================================== -->
        <section id="contact-section">
        <div style="margin-left: 490px; text-align: center;">
            <div class="container">
                <div class="row">
                    <div class="col-md-6">
                        <div class="block">
                            <h2 class="subtitle wow fadeInDown" data-wow-duration="500ms" data-wow-delay=".2s">Contáctame!!</h2>
                            <p class="subtitle-des wow fadeInDown" data-wow-duration="500ms" data-wow-delay=".4s">
                                Si te ha gustado alguno de mis portafolios, puedes contactarte conmigo llenando el formulario.
                            </p>
                            <div class="contact-form">
                                <form id="contact-form" method="post" action="{{ route('messages') }}" role="form">
                                <!-- Protección de aplicación contra ataques de falsificación de solicitudes entre sitios (CSRF) -->
                                {{ csrf_field() }}
                                    <div class="form-group wow fadeInDown" data-wow-duration="500ms" data-wow-delay=".6s">
                                        <input type="text" placeholder="Nombre" class="form-control" name="name" id="name">
                                    </div>
                                    
                                    <div class="form-group wow fadeInDown" data-wow-duration="500ms" data-wow-delay=".8s">
                                        <input type="email" placeholder="Correo" class="form-control" name="email" id="email" >
                                    </div>
                                    
                                    <div class="form-group wow fadeInDown" data-wow-duration="500ms" data-wow-delay="1s">
                                        <input type="text" placeholder="Asunto" class="form-control" name="subject" id="subject">
                                    </div>
                                    
                                    <div class="form-group wow fadeInDown" data-wow-duration="500ms" data-wow-delay="1.2s">
                                        <textarea rows="6" placeholder="Mensaje" class="form-control" name="body" id="message"></textarea>    
                                    </div>
                                    
                                    
                                    <div id="submit" class="wow fadeInDown" data-wow-duration="500ms" data-wow-delay="1.4s">
                                        <input type="submit" id="contact-submit" class="btn btn-default btn-send" value="Enviar">
                                    </div>                      
                                    
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        </section>

        
@endsection

resources/views/Inicio.blade.php
@extends('layoutM')

@section('content')
	 <!--
        ==================================================
        Slider Section Start
        ================================================== -->
        <section id="hero-area" class="hero-area" >
            <div class="container">
                <div class="row">
                    <div class="col-md-12 text-center">
                        <div class="block wow fadeInUp" data-wow-delay=".3s">
                            
                            <!-- Slider -->
                            <section class="cd-intro">
                                <h1 class="wow fadeInUp animated cd-headline slide" data-wow-delay=".4s" >
                                <span>Hola, mi nombre es Daniel Ramírez</span><br>
                                <span class="cd-words-wrapper">
                                    <b class="is-visible">Análisis y</b>
                                    <b>Desarrollo de</b>
                                    <b>Sistemas de información</b>
                                </span>
                                </h1>
                                </section> <!-- cd-intro -->
                                <!-- /.slider -->
                                <h2 class="wow fadeInUp animated" data-wow-delay=".6s" >
                                    Siendo técnico en Programación de software y 
                                    ahora estudiando tecnólogo en <br>
                                    ADSI
                                </h2>                                
                            </div>
                        </div>
                    </div>
                </div>
            </section><!--/#main-slider-->

             <!--
            ==================================================
            Slider Section Start
            ================================================== -->
            <section id="about" class="about">
                <div class="container">
                    <div class="section-heading">
                        <div class="col-md-6 col-sm-6">
                                <h2 class="title wow fadeInDown" data-wow-delay=".3s" style="margin-top: 150px;">
                                ABOUT ME
                                </h2>
                                <p>
                                    Hola, mi nombre es José Daniel Ramírez Ramírez, soy técnico en Programación de software por el Sena (2015-2016), estoy estudiando Análisis y Desarrollo de Sistemas de Información en el Sena.  
                                </p>
                                <a class="btn-lines dark light wow fadeInUp animated smooth-scroll btn btn-default btn-green" data-wow-delay=".9s" href="SobreMi">Ver más...</a>
                            </div>
                            
                        </div>
                        <div class="col-md-6 col-sm-6">
                            <div class="block wow fadeInRight" data-wow-delay=".3s" data-wow-duration="500ms">
                                <img src="images/Meme.jpeg" alt="">
                            </div>
                        </div>
                    </div>
                </div>
            </section> <!-- /#about -->

             <!--
            ==================================================
            Portfolio Section Start
            ================================================== -->
            <section id="prtafolio" class="prtafolio">
                <div class="container">
                    <div class="section-heading">
                        <h1 class="title wow fadeInDown" data-wow-delay=".3s">PRTAFOLIOS</h1>
                        <p class="wow fadeInDown" data-wow-delay=".5s">
                            Veras todos mis trabajos solo hechos por mi. Miralos sin compromiso.
                        </p>
                    </div>
                    <div class="row">
                        <div class="col-sm-4 col-xs-12">
                            <figure class="wow fadeInLeft animated portfolio-item" data-wow-duration="500ms" data-wow-delay="0ms">
                                <div class="img-wrapper">
                                    <img src="images/RedSocial.jpg" class="img-responsive" alt="this is a title" >
                                    <div class="overlay">
                                        <div class="buttons">
                                            <a rel="gallery" class="fancybox" href="images/RedSocial.jpg">Demo</a>
                                            <a target="_blank" href="single-portfolio.html">Ver más...</a>
                                        </div>
                                    </div>
                                </div>
                                <figcaption>
                                <h4>
                                <a href="#">
                                    Dew Drop
                                </a>
                                </h4>
                                <p>
                                    Redesigne UI Concept
                                </p>
                                </figcaption>
                            </figure>
                        </div>
                        <div class="col-sm-4 col-xs-12">
                            <figure class="wow fadeInLeft animated" data-wow-duration="500ms" data-wow-delay="300ms">
                                <div class="img-wrapper">
                                    <img src="images/LoginU.jpg" class="img-responsive" alt="this is a title" >
                                    <div class="overlay">
                                        <div class="buttons">
                                            <a rel="gallery" class="fancybox" href="images/LoginU.jpg">Demo</a>
                                            <a target="_blank" href="Portafolio">Ver más...</a>
                                        </div>
                                    </div>
                                </div>
                                <figcaption>
                                <h4>
                                <a href="#">
                                    Ejemplo
                                </a>
                                </h4>
                                <p>
                                    Lorem ipsum dolor sit.
                                </p>
                                </figcaption>
                            </figure>
                        </div>
                        <div class="col-sm-4 col-xs-12">
                            <figure class="wow fadeInLeft animated" data-wow-duration="500ms" data-wow-delay="300ms">
                                <div class="img-wrapper">
                                    <img src="images/ProyectoVS.jpg" class="img-responsive" alt="" >
                                    <div class="overlay">
                                        <div class="buttons">
                                            <a rel="gallery" class="fancybox" href="images/ProyectoVS.jpg">Demo</a>
                                            <a target="_blank" href="Portafolio">Ver más...</a>
                                        </div>
                                    </div>
                                </div>
                                <figcaption>
                                <h4>
                                <a href="#">
                                    Table Design
                                </a>
                                </h4>
                                <p>
                                    Lorem ipsum dolor sit amet.
                                </p>
                                </figcaption>
                            </figure>
                        </div><br>
                        <a class="btn-lines dark light wow fadeInUp animated smooth-scroll btn btn-default btn-green" data-wow-delay=".9s" href="Portafolio" style="margin-left: 530px; font-size: 18px;" >Ver más...</a>
                    </div>
                </div>
            </section> <!-- #works -->

            <!--
            ==================================================
            Portfolio Section Start
            ================================================== -->
            <section id="feature" class="feature">
                <div class="container">
                    <div class="section-heading">
                        <h1 class="title wow fadeInDown" data-wow-delay=".3s">Contacto</h1>
                        <h3 class="wow fadeInDown" data-wow-delay=".5s">
                            Contáctame tambien en mis redes sociales. 
                        </h3>
                    </div>
                    <div class="row">
                        <div class="col-md-4 col-lg-4 col-xs-12">
                            <div class="media wow fadeInUp animated" data-wow-duration="500ms" data-wow-delay="300ms">
                                <div class="media-left">
                                <div class="media-body">
                                    <h4 class="media-heading" style="margin-left: 13px;">FACEBOOK</h4>
                                </div>
                                    <div class="icon">
                                        <i class="ion-ios-flask-outline"></i>
                                    </div>
                                </div>
                                
                            </div>
                        </div>
                        <div class="col-md-4 col-lg-4 col-xs-12">
                            <div class="media wow fadeInDown animated" data-wow-duration="500ms" data-wow-delay="600ms">
                                <div class="media-left">
                                <div class="media-body">
                                    <h4 class="media-heading" style="margin-left: 18px;"">TWITTER</h4>   
                                </div>
                                    <div class="icon">
                                        <i class="ion-ios-lightbulb-outline"></i> 
                                    </div>
                                </div>
                                
                            </div>
                        </div>
                        <div class="col-md-4 col-lg-4 col-xs-12">
                            <div class="media wow fadeInDown animated" data-wow-duration="500ms" data-wow-delay="900ms">
                                <div class="media-left">
                                <div class="media-body">
                                    <h4 class="media-heading">INSTAGRAM</h4>
                                </div>
                                    <div class="icon">
                                        <i class="ion-ios-lightbulb-outline"></i> 
                                    </div>
                                </div>
                                
                            </div>
                        </div>
                        <a class="btn-lines dark light wow fadeInUp animated smooth-scroll btn btn-default btn-green" data-wow-delay=".9s" href="contacto" style="margin-left: 540px; font-size: 18px;" >Ver más...</a>
                    </div>
                </div>
            </section> <!-- /#feature -->

            <span class="ir-arriba icon-arrow-with-circle-up"></span>


@endsection
 

resources/views/Login.blade.php
<h1>Login</h1>

resources/views/Portafolio.blade.php
@extends('layout')

@section('content')
	<!-- 
        ================================================== 
            Global Page Section Start
        ================================================== -->
        <section class="global-page-header">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <div class="block">
                            <h2>Portafolio</h2>
                        </div>
                    </div>
                </div>
            </div>   
        </section><!--/#Page header-->


         <section class="company-description">
            <div class="container">
                <div class="row">
                    <div class="col-md-6 wow fadeInLeft" data-wow-delay=".3s" >
                        <img src="images/RedSocial.jpg" alt="" class="img-responsive">
                    </div>
                    <div class="col-md-6">
                        <div class="block">
                            <h3 class="subtitle wow fadeInUp" data-wow-delay=".3s" data-wow-duration="500ms">Pagina Red social</h3>
                            <p  class="wow fadeInUp" data-wow-delay=".5s" data-wow-duration="500ms">
                                
                            </p>
                            <h3  class="wow fadeInUp" data-wow-delay=".7s" data-wow-duration="500ms">
                                Diseño y programación: hecho por Daniel Ramírez en maquetación Html5, CSS y Jquery. 
                            </h3>

                            <h3  class="wow fadeInUp" data-wow-delay=".7s" data-wow-duration="500ms">
                               Realizado: de Febrero a Marzo de 2017. 
                            </h3>
                            
                        </div>
                    </div>
                </div>
            </div>
        </section>
        </br>
        <section class="company-description">
            <div class="container">
                <div class="row">
                    <div class="col-md-6">
                        <div class="block">
                            <h3 class="subtitle wow fadeInUp" data-wow-delay=".3s" data-wow-duration="500ms">Pagina Login</h3>
                            
                            <h3  class="wow fadeInUp" data-wow-delay=".7s" data-wow-duration="500ms">
                                Diseño y programación: hecho por Daniel Ramírez en maquetación Html5 y CSS. 
                            </h3>

                            <h3  class="wow fadeInUp" data-wow-delay=".7s" data-wow-duration="500ms">
                               Realizado:  Febrero y marzo de 2017.
                            </h3>
                            
                        </div>
                    </div>
                    <div class="col-md-6 wow fadeInLeft" data-wow-delay=".3s" >
                        <img src="images/LoginU.jpg" alt="" class="img-responsive">
                    </div>
                </div>
            </div>
        </section>

        <section class="company-description">
            <div class="container">
                <div class="row">
                <div class="col-md-6 wow fadeInLeft" data-wow-delay=".3s" >
                        <img src="images/ProyectoVS.jpg" alt="" class="img-responsive">
                    </div>
                    <div class="col-md-6">
                        <div class="block">
                            <h3 class="subtitle wow fadeInUp" data-wow-delay=".3s" data-wow-duration="500ms">Proyecto de calzado</h3>
                            
                            <h3  class="wow fadeInUp" data-wow-delay=".7s" data-wow-duration="500ms">
                                Diseño y programación: hecho por Daniel Ramírez y Brayan Triana (amigo) en Visual Studio. Este proyecto se hizo durante el técnico.</h3> 
                                <h3  class="wow fadeInUp" data-wow-delay=".7s" data-wow-duration="500ms">Un proyecto de un almacen de calzado donde requeria un sistema de información para la gestion de inventario, ventas y pagos del almacen.
                                </h3>

                            <h3  class="wow fadeInUp" data-wow-delay=".7s" data-wow-duration="500ms">
                               Realizado:  2015 - 2016.
                            </h3>
                            
                        </div>
                    </div>
                    
                </div>
            </div>
        </section>


@endsection

resources/views/SobreMi.blade.php
@extends('layout')

@section('content')
	<!-- 
        ================================================== 
            Global Page Section Start
        ================================================== -->
        <section class="global-page-header">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <div class="block">
                            <h2>Sobre mí</h2>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <!-- 
        ================================================== 
            Company Description Section Start
        ================================================== -->
        <section class="company-description">
            <div class="container">
                <div class="row">
                    <div class="col-md-6 wow fadeInLeft" data-wow-delay=".3s" >
                        <img src="images/GatoCity.jpg" alt="" class="img-responsive">
                    </div>
                    <div class="col-md-6">
                        <div class="block">
                            <h3 class="subtitle wow fadeInUp" data-wow-delay=".3s" data-wow-duration="500ms">Daniel Ramírez</h3>
                            <p  class="wow fadeInUp" data-wow-delay=".5s" data-wow-duration="500ms">
                                Estudiante de Análisis y Desarrollo de Sistemas de información
                            </p>
                            <h3  class="wow fadeInUp" data-wow-delay=".7s" data-wow-duration="500ms">
                                
                            </h3>
                            
                        </div>
                    </div>
                </div>
            </div>
        </section>
        
        
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Dashboard</div>

                <div class="panel-body">
                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/images.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
	<div class="row">
		{!! Form::open(['route' => 'image.store', 'method'=> 'post', 'novalidate']) !!}

			{!! Form::label('id') !!}

			{!! Form::number('id',null,['class'=>'form-control'])!!}
			
			{!! Form::label('Seleccion') !!}

			{!! Form::file('images',null,['class'=>'form-control'])!!}	
			{!! Form::submit('Enviar',['class'=>'btn-btn-primary'])!!}
		{!! Form::close() !!}
	</div>
</div>
@endsection

resources/views/listimage.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
	<div class="row">
		{!!Form::open(['route'=>'image/search','method'=>'post','novalidate','class'=>'form-inline'])!!}
		<div class="form-group">
			<label>Id</label>
			<input type="number" name="name" class="form-control">
		</div>
		<div class="form-group">
			<button type="submit" class="btn btn-primary">Buscar</button>
			<a href="{{ route('image.index')}}" class="btn btn-primary">Todo</a>
			<a href="{{ route('image.create')}}" class="btn btn-primary">Crear</a>
		</div>
		{!!Form::close()!!}
	</div>
	<div class="row">
		<table class="table table-bordered table-striped table-condensed">
			<thead>
				<tr>
					<th>id</th>
					<th>Foto</th>
				</tr>
			</thead>
			<tbody>
				@foreach($images as $image)
				<tr>
					<td>{{$image->id}}</td>
					<td>{{$image->images}}</td>
				</tr>
				@endforeach
			</tbody>
		</table>
	</div>
	
</div>
@endsection